name: mobile_tumbuh_sehat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  dio: ^5.8.0+1
  http_parser: ^4.0.2
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  go_router: ^16.0.0
  freezed_annotation: ^3.1.0
  lottie: ^3.3.1
  web_socket_channel: ^3.0.3
  hive: ^2.2.3
  skeletonizer: ^2.1.0+1
  envied: ^1.1.1
  flutter_gen_runner: ^5.11.0
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  freezed: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    # - lib/assets/icon
    - lib/assets/image/Splash Screen Illustration.svg
    - lib/assets/image/Logo.svg

flutter_gen:
  output: lib/app/core/gen/
  line_length: 80

targets:
  $default:
    builders:
      json_serializable:
        options:
          constructor: ""
          explicit_to_json: true